spring:
  application:
    name: Modal JS

  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydbtest?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: bestuser
    password: bestuser

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    enabled: true
    enable-spring-el-compiler: true

server:
  port: 8080

